#
#    See the NOTICE file distributed with this work for additional information
#    regarding copyright ownership.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

stages:
  - test
  - build
  - deploy

# Deployment template
.deploy:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.4
  before_script:
    - cd k8s/base
  script:
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize build . | kubectl apply -f -

# Run Tests
Test:
  stage: test
  image: python:3.10
  before_script:
    - pip install app/tests/requirements.txt
  script:
    - pytest --cov --junitxml=report.xml
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
  except:
    - /^skiptest\/.*$/

# Build the docker image
Docker:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${DOCKER_IMAGE} --no-cache .
    - docker push ${DOCKER_IMAGE}
    - docker rmi ${DOCKER_IMAGE}
    - docker logout $CI_REGISTRY

# Deploy feature branch (for specific review apps)
Review:HX:
  extends: .deploy
  environment:
    name: wp-hx-dev
    on_stop: Stop_review
  before_script:
    - cd k8s/overlays/review
    - kustomize edit set label environment:${CI_COMMIT_REF_SLUG}
    - kustomize edit set namesuffix -- -${CI_COMMIT_REF_SLUG}
  except:
    - main
    - dev

# Stop feature branch review app (cleanup resources) 
Stop_review:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.4
  environment:
    name: wp-hx-dev
    action: stop
  variables:
    GIT_STRATEGY: none
  when: manual
  except:
    - main
    - dev
  script:
    - kubectl delete service ensembl-tools-api-svc-${CI_COMMIT_REF_SLUG}
    - kubectl delete deploy ensembl-tools-api-deployment-${CI_COMMIT_REF_SLUG}

# Deploy main branch to HX dev (default BE for review apps)
Dev:HX:
  extends: .deploy
  environment:
    name: wp-hx-dev
  before_script:
    - cd k8s/overlays/development
    - kustomize edit set label environment:dev
  only:
    - main

# Deploy dev branch to staging
Staging:HX:
  extends: .deploy
  environment:
    name : wp-hx-staging
  before_script:
    - cd k8s/overlays/staging
  only:
    - dev

Staging:HL:
  extends: .deploy
  environment:
    name : wp-hh-staging
  before_script:
    - cd k8s/overlays/staging
  only:
    - dev

# Deploy main branch to internal
Internal:HX:
  extends: .deploy
  environment:
    name : wp-hx-internal
  before_script:
    - cd k8s/overlays/internal
  only:
    - main

Internal:HL:
  extends: .deploy
  environment:
    name : wp-hh-internal
  before_script:
    - cd k8s/overlays/internal
  only:
    - main

# Deploy main to production (manual confirmation)
Production:HX:
  extends: .deploy
  environment:
    name : wp-hx-live
  before_script:
    - cd k8s/overlays/production
  only:
    - main
  when: manual

Production:HL:
  extends: .deploy
  environment:
    name : wp-hh-live
  before_script:
    - cd k8s/overlays/production
  only:
    - main
  when: manual
