openapi: 3.0.0
info:
  title: Tools api
  version: 0.0.1
paths:
  /api/tools/vep/submissions/{id}/results:
    get:
      description: Returns results of VEP analysis
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: number
            default: 1
        - name: per_page
          in: query
          required: false
          schema:
            type: number
            default: 100
      responses:
        '200':
          description: Successful operaiton.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VepResultsResponse'
components:
  schemas:
    AlternativeVariantAllele:
      type: object
      required:
        - allele_sequence
        - allele_type
        - predicted_molecular_consequences
      properties:
        allele_sequence:
          type: string
        allele_type:
          type: string
        representative_population_allele_frequency:
          type: number
          nullable: true
        predicted_molecular_consequences:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/PredictedTranscriptConsequence'
              - $ref: '#/components/schemas/PredictedIntergenicConsequence'
    PaginationMetadata:
      type: object
      required:
        - page
        - per_page
        - total
      properties:
        page:
          type: number
        per_page:
          type: number
        total:
          type: number
    PredictedIntergenicConsequence:
      type: object
      required:
        - feature_type
        - consequences
      properties:
        feature_type:
          nullable: true
          description: The value of this field is always null. The presence of null in this field will serve as a marker that this is a consequence of an intergenic variant.
        consequences:
          type: array
          items:
            type: string
          description: The only expected member of this array will be the string 'intergenic_variant'
    PredictedTranscriptConsequence:
      type: object
      required:
        - feature_type
        - stable_id
        - gene_stable_id
        - gene_symbol
        - biotype
        - is_canonical
        - consequences
        - strand
      properties:
        feature_type:
          type: string
          enum:
            - transcript
        stable_id:
          type: string
          description: transcript stable id, versioned
        gene_stable_id:
          type: string
          description: gene stable id, versioned
        gene_symbol:
          type: string
          nullable: true
        biotype:
          type: string
        is_canonical:
          type: boolean
        consequences:
          type: array
          items:
            type: string
        strand:
          type: string
          enum:
            - forward
            - reverse
    ReferenceVariantAllele:
      type: object
      required:
        - allele_sequence
      properties:
        allele_sequence:
          type: string
    Variant:
      type: object
      required:
        - name
        - allele_type
        - slice
        - reference_allele
        - alternative_alleles
      properties:
        name:
          type: string
          nullable: true
          description: User's name for the variant; optional
        location:
          type: object
          properties:
            region_name:
              type: string
            start:
              type: number
            end:
              type: number
          required:
            - region_name
            - start
            - end
        reference_allele:
          $ref: '#/components/schemas/ReferenceVariantAllele'
        alternative_alleles:
          type: array
          items:
            $ref: '#/components/schemas/AlternativeVariantAllele'
    VepResultsResponse:
      type: object
      required:
        - metadata
        - variants
      properties:
        metadata:
          type: object
          properties:
            pagination:
              $ref: '#/components/schemas/PaginationMetadata'
          required:
            - pagination
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Variant'
