version: '2'
services:
  tools_api:
    env_file:
      - ./app/.env
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "uvicorn main:app --proxy-headers --lifespan on --host 0.0.0.0 --port 8013 --reload"
    container_name: tools-api
    environment:
      - DEBUG=True
    volumes:
      - ./app/:/app/
      - ./tmpdir:/nfs/public/rw/enswbsites
    ports:
      - 8013:8013
