name: Delete removed GitHub branch from GitLab remote

on:
  delete:
    branches-igore:
      - main
      - dev

jobs:
  branch-delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITLAB_TOKEN }}
      REPO: ${{ github.event.repository.name }}
      BRANCH: ${{ github.event.ref }}
    steps:
      - name: Send branch delete request
        run: |
          curl --request DELETE --header "PRIVATE-TOKEN: $TOKEN" "https://gitlab.com/api/v4/projects/ensembl-web/$REPO/repository/branches/$BRANCH"