apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ensembl-stage
bases:
  - ../../base
  - ../../base/ingress.yaml
patches:
  - target:
      kind: Ingress
      name: ensembl-tools-api-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging-2020.ensembl.org